### PR TITLE
fix!: update log and data dirs for linux and windows

### LINKED ISSUE #74: [错误] 必须使用 root 权限执行
### 错误描述

当安装 OpenList Desktop 之后，必须使用 root 用户启动才可正常使用，否则软件会自动退出。

### 重现步骤

1. 在 `Linux Mint 22.1 x86_64` 上安装 `https://github.com/OpenListTeam/OpenList-Desktop/releases/download/v0.6.1/OpenList.Desktop_0.6.1_amd64.deb`（sudo apt -f install ./文件名.deb）。
2. 在菜单搜索 OpenList，打开 OpenList Desktop。
3. 软件在任务栏出现图标，随即消失。
4. 在命令行执行：
```bash
$ openlist-desktop
```
有如下输出：
```bash
thread 'main' panicked at src/utils/init_log.rs:22:10:
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "权限不够" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
已中止 (核心已转储)
```
5. 执行：
```bash
$ sudo openlist-desktop
```
输入密码后回车，软件出现主界面，命令行输出：
```bash
(openlist-desktop:73954): Gdk-CRITICAL **: 22:57:24.753: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

### 预期行为

无需 root 权限，直接打开菜单中的图标即可使用。

### 实际行为

软件在出现图标后就消失了。

### 操作系统

其他 Linux 发行版

### 系统架构

x64 (64位)

### OpenList Desktop 版本

0.6.1

### 应用程序日志

```shell
软件无法启动，没有日志。
```

### 其他信息

Image

### 检查清单

- [x] 我已搜索现有问题以确保这不是重复问题
- [x] 我已提供所有必需的环境信息
- [x] 我可以稳定地重现此问题

### LINKED ISSUE #107: [错误] Linux下data dir获取问题
### 错误描述

在Linux下，可执行文件默认被安装到 `/usr/bin` 当中。按照[此函数](https://github.com/OpenListTeam/OpenList-Desktop/blob/e00c0d5ffd2ddc5e2446554cc62a801086f8004b/src-tauri/src/utils/path.rs#L19) 的描述，在非macOS平台，get_user_data_dir 将返回可执行文件目录。然而，`/usr/bin` 目录对于普通用户是不可写的，且也不应该在此目录下储存数据。

### 重现步骤

在 Debian 系Linux发行版中安装deb，在终端中执行 openlist-desktop 即可复现

### 预期行为

程序成功启动，且配置文件储存在正确的文件夹下，如 `/home/user/.local/` 或 `/home/user/.config` 中。

### 实际行为

程序尝试将数据存储在 `/usr/bin`。普通用户无法写入该目录，导致程序无法启动。

### 操作系统

其他 Linux 发行版

### 系统架构

x64 (64位)

### OpenList Desktop 版本

v0.7.0

### 应用程序日志

```shell
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/ceca157a-2953-4caa-955b-300994b4b55c" />
```

### 其他信息

_No response_

### 检查清单

- [x] 我已搜索现有问题以确保这不是重复问题
- [x] 我已提供所有必需的环境信息
- [x] 我可以稳定地重现此问题

### PR DESCRIPTION
**Pull request by elysia-best**
fixes #107
may also fix #74

BREAKING CHANGE: data dir changed. Users may need to move the data dir manually.

### CODE REVIEW

File: src-tauri/src/utils/path.rs [hunk 1]
```diff
@@ -29,9 +29,26 @@ fn get_user_data_dir() -> Result<PathBuf, String> {
...
 
-    #[cfg(not(target_os = "macos"))]
+    #[cfg(target_os = "linux")]
+    {
+        let home = env::var("HOME").map_err(|_| "Failed to get HOME environment variable")?;
+        let data_dir = PathBuf::from(home)
+            .join(".local")
+            .join("share")
+            .join("OpenList Desktop");
+        fs::create_dir_all(&data_dir)
```
Comment (cxw620) [inline src-tauri/src/utils/path.rs:39]: IMO only the logic obtaining data dir varies between platforms that needs to be gated behind `target_os`.

File: src-tauri/src/utils/path.rs [hunk 2]
```diff
@@ -29,9 +29,26 @@ fn get_user_data_dir() -> Result<PathBuf, String> {
...
+
+    #[cfg(target_os = "windows")]
     {
-        get_app_dir()
+        let appdata =
+            env::var("APPDATA").map_err(|_| "Failed to get APPDATA environment variable")?;
+        let data_dir = PathBuf::from(appdata).join("OpenList Desktop");
+        fs::create_dir_all(&data_dir)
+            .map_err(|e| format!("Failed to create data directory: {e}"))?;
+        Ok(data_dir)
```
Comment (cxw620) [inline src-tauri/src/utils/path.rs:51]: IMO we should canonicalize the returned dir.

**Review by cxw620 — APPROVED** [review]
